/**
 * Azure DevOps & Azure Data Engineering learning paths
 */
function s(slug, label, description, extra = {}) {
  return { slug, label, description, ...extra };
}

const AZURE_DEVOPS_PATHS = {
  'azure-fundamentals': [
    s('cloud-overview', 'Cloud Computing Overview', 'On-premises vs cloud, benefits, and shared responsibility model.'),
    s('iaas-paas-saas', 'IaaS, PaaS, SaaS', 'Service models and choosing the right Azure offering.'),
    s('azure-regions', 'Azure Regions & Zones', 'Geography, availability zones, and region pairing.'),
    s('subscriptions', 'Subscriptions & Management Groups', 'Organizing Azure resources and billing boundaries.'),
    s('resource-groups', 'Resource Groups', 'Logical containers, tags, and lifecycle management.'),
    s('azure-portal', 'Azure Portal', 'Navigating the portal, resource blades, and Cloud Shell.'),
    s('azure-cli', 'Azure CLI Basics', 'Installing az CLI, login, and common commands.', { codeLang: 'bash' }),
    s('azure-powershell', 'Azure PowerShell', 'Connect-AzAccount and cmdlet-based management.'),
    s('compute-overview', 'Compute Services', 'VMs, App Service, AKS, Functions, and Container Instances.'),
    s('storage-overview', 'Storage Services', 'Blob, File, Queue, Table, and Disk storage options.'),
    s('networking-overview', 'Networking Overview', 'VNets, subnets, NSGs, and Azure DNS.'),
    s('identity-overview', 'Identity Overview', 'Microsoft Entra ID, users, groups, and applications.'),
    s('rbac-basics', 'RBAC Basics', 'Roles, scopes, and least-privilege access in Azure.'),
    s('cost-management', 'Cost Management', 'Pricing calculator, budgets, alerts, and reservations.'),
    s('monitoring-overview', 'Monitoring Overview', 'Azure Monitor, Log Analytics, and Application Insights.'),
    s('well-architected', 'Well-Architected Framework', 'Five pillars: reliability, security, cost, operations, performance.'),
    s('arm-templates-intro', 'ARM Templates Intro', 'Declarative infrastructure as code with JSON templates.'),
    s('bicep-intro', 'Bicep Introduction', 'Simplified ARM syntax and deployment workflows.'),
    s('azure-marketplace', 'Azure Marketplace', 'Third-party solutions and SaaS offerings in Azure.'),
    s('certification-path', 'Certification Path', 'AZ-900, AZ-104, and role-based certification roadmap.'),
  ],

  'azure-repos': [
    s('git-fundamentals', 'Git Fundamentals', 'Commits, branches, remotes, and the Git object model.'),
    s('azure-repos-setup', 'Azure Repos Setup', 'Creating repos, cloning, and authentication methods.'),
    s('branching-strategy', 'Branching Strategy', 'GitFlow, trunk-based, and feature branch workflows.'),
    s('commits-best-practices', 'Commit Best Practices', 'Atomic commits, messages, and conventional commits.'),
    s('pull-requests', 'Pull Requests', 'Creating PRs, descriptions, and linking work items.'),
    s('code-review', 'Code Review', 'Review checklist, constructive feedback, and approval policies.'),
    s('branch-policies', 'Branch Policies', 'Required reviewers, build validation, and merge types.'),
    s('merge-strategies', 'Merge Strategies', 'Merge commit, squash, rebase, and when to use each.'),
    s('conflict-resolution', 'Conflict Resolution', 'Merge conflicts, rebase conflicts, and resolution tools.'),
    s('tags-releases', 'Tags & Releases', 'Semantic versioning, Git tags, and release notes.'),
    s('hooks-webhooks', 'Hooks & Webhooks', 'Server hooks, service hooks, and automation triggers.'),
    s('repo-permissions', 'Repo Permissions', 'Contributors, readers, and security group integration.'),
    s('fork-workflows', 'Fork Workflows', 'Forking, syncing, and contributing to upstream repos.'),
    s('integration-ide', 'IDE Integration', 'VS Code, Visual Studio, and Git credential management.'),
    s('repos-capstone', 'Repos Capstone', 'Set up a repo with branch policies and PR workflow.'),
  ],

  'azure-pipelines': [
    s('pipelines-overview', 'Pipelines Overview', 'Build vs release, YAML vs classic, and pipeline anatomy.'),
    s('yaml-structure', 'YAML Structure', 'trigger, pool, stages, jobs, and steps hierarchy.'),
    s('first-pipeline', 'Your First Pipeline', 'Create a CI pipeline that builds and tests code.'),
    s('triggers', 'Triggers', 'CI triggers, PR triggers, scheduled, and path filters.'),
    s('variables', 'Variables & Variable Groups', 'Pipeline variables, secrets, and library groups.'),
    s('templates', 'YAML Templates', 'Reusable templates, parameters, and template composition.'),
    s('build-agents', 'Build Agents', 'Microsoft-hosted vs self-hosted agents and agent pools.'),
    s('agent-pools', 'Agent Pools', 'Creating pools, agent capabilities, and parallel jobs.'),
    s('artifacts', 'Pipeline Artifacts', 'Publishing, downloading, and artifact retention policies.'),
    s('caching', 'Pipeline Caching', 'Dependency caching for faster builds.'),
    s('multi-stage', 'Multi-Stage Pipelines', 'Stages, dependencies, conditions, and approvals.'),
    s('deployment-jobs', 'Deployment Jobs', 'Environment deployment, runOnce, rolling, and canary strategies.'),
    s('environments', 'Environments', 'Environment resources, checks, and deployment history.'),
    s('service-connections', 'Service Connections', 'Azure RM, Docker Registry, and GitHub connections.'),
    s('testing-gates', 'Testing Gates', 'Unit tests, code coverage, and quality gates in pipelines.'),
    s('security-scanning', 'Security Scanning', 'SAST, dependency scanning, and credential scanning.'),
    s('release-pipelines', 'Release Pipelines', 'Classic release pipelines vs YAML multi-stage.'),
    s('pipeline-permissions', 'Pipeline Permissions', 'OAuth, PAT, and pipeline resource authorization.'),
    s('monitoring-pipelines', 'Monitoring Pipelines', 'Analytics, failure trends, and pipeline dashboards.'),
    s('pipeline-patterns', 'Pipeline Patterns', 'Monorepo, microservices, and infrastructure pipelines.'),
    s('capstone-pipeline', 'Pipeline Capstone', 'Build a full CI/CD pipeline with test and deploy stages.'),
  ],

  'ci-cd': [
    s('cicd-overview', 'CI/CD Overview', 'Continuous integration, delivery, and deployment definitions.'),
    s('ci-principles', 'CI Principles', 'Frequent commits, automated builds, and fast feedback loops.'),
    s('cd-principles', 'CD Principles', 'Automated releases, deployment pipelines, and rollback.'),
    s('pipeline-design', 'Pipeline Design', 'Stage ordering, artifact flow, and environment promotion.'),
    s('branching-cicd', 'Branching for CI/CD', 'Feature branches, main protection, and release branches.'),
    s('automated-testing', 'Automated Testing in CI', 'Unit, integration, and E2E tests in the pipeline.'),
    s('deployment-strategies', 'Deployment Strategies', 'Blue-green, canary, rolling, and feature flags.'),
    s('infrastructure-cicd', 'Infrastructure CI/CD', 'Terraform/Bicep in pipelines and IaC validation.'),
    s('database-cicd', 'Database CI/CD', 'Schema migrations, flyway, and database deployment patterns.'),
    s('container-cicd', 'Container CI/CD', 'Build, scan, push, and deploy container images.'),
    s('gitops', 'GitOps', 'Declarative deployments, Argo CD, and Flux concepts.'),
    s('feature-flags', 'Feature Flags', 'Progressive delivery and LaunchDarkly-style rollouts.'),
    s('rollback-strategies', 'Rollback Strategies', 'Automated rollback, health checks, and smoke tests.'),
    s('environment-config', 'Environment Configuration', 'Dev, staging, prod parity and config management.'),
    s('secrets-cicd', 'Secrets in CI/CD', 'Key Vault integration, secret rotation, and pipeline security.'),
    s('compliance-gates', 'Compliance Gates', 'Audit trails, approval workflows, and change management.'),
    s('dora-metrics', 'DORA Metrics', 'Deployment frequency, lead time, MTTR, and change failure rate.'),
    s('cicd-maturity', 'CI/CD Maturity Model', 'Assessing and improving your delivery pipeline maturity.'),
    s('trunk-based', 'Trunk-Based Development', 'Short-lived branches and continuous integration at scale.'),
    s('cicd-capstone', 'CI/CD Capstone', 'Design a CI/CD strategy for a microservices application.'),
  ],

  docker: [
    s('containers-overview', 'Containers Overview', 'Containers vs VMs, isolation, and portability benefits.'),
    s('docker-installation', 'Docker Installation', 'Docker Desktop, Engine, and verifying installation.'),
    s('images-containers', 'Images & Containers', 'Image layers, container lifecycle, and immutability.'),
    s('dockerfile', 'Dockerfile', 'FROM, RUN, COPY, CMD, ENTRYPOINT, and best practices.'),
    s('building-images', 'Building Images', 'docker build, tags, and .dockerignore.'),
    s('running-containers', 'Running Containers', 'docker run, ports, volumes, and environment variables.'),
    s('docker-compose', 'Docker Compose', 'Multi-container apps, compose files, and local development.'),
    s('networking', 'Docker Networking', 'Bridge, host, overlay networks, and service discovery.'),
    s('volumes', 'Docker Volumes', 'Named volumes, bind mounts, and data persistence.'),
    s('multi-stage-builds', 'Multi-Stage Builds', 'Smaller production images with build and runtime stages.'),
    s('docker-registry', 'Container Registry', 'Docker Hub, ACR, and image tagging strategies.'),
    s('acr-setup', 'Azure Container Registry', 'Creating ACR, authentication, and geo-replication.'),
    s('security-scanning', 'Image Security Scanning', 'Vulnerability scanning and base image selection.'),
    s('dockerignore', 'Optimizing Builds', '.dockerignore, layer caching, and build context size.'),
    s('health-checks', 'Health Checks', 'HEALTHCHECK instruction and container orchestration readiness.'),
    s('debugging-containers', 'Debugging Containers', 'docker logs, exec, inspect, and common issues.'),
    s('docker-production', 'Docker in Production', 'Resource limits, restart policies, and orchestration handoff.'),
    s('docker-capstone', 'Docker Capstone', 'Containerize a web app with Compose and push to ACR.'),
  ],

  kubernetes: [
    s('k8s-overview', 'Kubernetes Overview', 'Orchestration, control plane, and worker node architecture.'),
    s('cluster-architecture', 'Cluster Architecture', 'API server, etcd, scheduler, controller manager, kubelet.'),
    s('kubectl-basics', 'kubectl Basics', 'Config, get, describe, apply, and delete commands.'),
    s('pods', 'Pods', 'Pod lifecycle, multi-container pods, and restart policies.'),
    s('deployments', 'Deployments', 'ReplicaSets, rolling updates, and rollback.'),
    s('services', 'Services', 'ClusterIP, NodePort, LoadBalancer, and service discovery.'),
    s('configmaps', 'ConfigMaps', 'Configuration data injection via env vars and volumes.'),
    s('secrets', 'Secrets', 'Secret management, base64 encoding, and external secret operators.'),
    s('ingress', 'Ingress', 'Ingress controllers, rules, TLS, and path-based routing.'),
    s('namespaces', 'Namespaces', 'Resource isolation, quotas, and multi-tenancy.'),
    s('labels-selectors', 'Labels & Selectors', 'Labeling resources and selector-based operations.'),
    s('resource-limits', 'Resource Limits', 'Requests, limits, QoS classes, and resource quotas.'),
    s('health-probes', 'Health Probes', 'Liveness, readiness, and startup probes.'),
    s('persistent-volumes', 'Persistent Volumes', 'PV, PVC, StorageClass, and dynamic provisioning.'),
    s('statefulsets', 'StatefulSets', 'Stable network identity and ordered deployment for stateful apps.'),
    s('daemonsets', 'DaemonSets', 'Running pods on every node for logging and monitoring agents.'),
    s('jobs-cronjobs', 'Jobs & CronJobs', 'Batch workloads and scheduled tasks in Kubernetes.'),
    s('helm-intro', 'Helm Introduction', 'Charts, releases, and package management for K8s.'),
    s('network-policies', 'Network Policies', 'Pod-to-pod traffic control and micro-segmentation.'),
    s('troubleshooting', 'Troubleshooting K8s', 'Common failure modes, events, and debugging workflows.'),
    s('k8s-capstone', 'Kubernetes Capstone', 'Deploy a multi-tier app with Deployment, Service, and Ingress.'),
  ],

  aks: [
    s('aks-overview', 'AKS Overview', 'Managed Kubernetes on Azure and integration benefits.'),
    s('cluster-creation', 'Creating AKS Clusters', 'az aks create, node pools, and cluster options.'),
    s('node-pools', 'Node Pools', 'System vs user pools, VM sizes, and spot instances.'),
    s('networking-aks', 'AKS Networking', 'Kubenet vs Azure CNI, VNet integration, and IP planning.'),
    s('identity-aks', 'AKS Identity', 'Managed identity, AAD integration, and RBAC.'),
    s('scaling-hpa', 'Horizontal Pod Autoscaler', 'CPU/memory-based scaling and custom metrics.'),
    s('cluster-autoscaler', 'Cluster Autoscaler', 'Node pool scaling based on pod demand.'),
    s('azure-monitor-aks', 'Monitoring AKS', 'Container Insights, metrics, and log queries.'),
    s('ingress-aks', 'Ingress on AKS', 'Application Gateway Ingress Controller and NGINX.'),
    s('storage-aks', 'Storage on AKS', 'Azure Disk, Azure Files, and persistent volume claims.'),
    s('secrets-aks', 'Secrets on AKS', 'Key Vault CSI driver and secret rotation.'),
    s('upgrades-aks', 'AKS Upgrades', 'Kubernetes version upgrades and node image updates.'),
    s('security-aks', 'AKS Security', 'Pod security, network policies, and Azure Policy.'),
    s('devops-aks', 'DevOps for AKS', 'CI/CD pipelines deploying to AKS with Helm or manifests.'),
    s('cost-optimization-aks', 'AKS Cost Optimization', 'Spot nodes, right-sizing, and cluster autoscaler tuning.'),
    s('aks-capstone', 'AKS Capstone', 'Deploy and monitor an application on AKS with autoscaling.'),
  ],

  terraform: [
    s('terraform-overview', 'Terraform Overview', 'Infrastructure as code, providers, and declarative model.'),
    s('hcl-basics', 'HCL Basics', 'Resources, data sources, variables, and outputs syntax.'),
    s('first-config', 'First Configuration', 'Write and apply a simple Azure resource with Terraform.'),
    s('providers', 'Providers', 'azurerm provider, version constraints, and provider configuration.'),
    s('state-local', 'Local State', 'terraform.tfstate, state file importance, and sensitivity.'),
    s('state-remote', 'Remote State', 'Azure Storage backend, state locking, and team collaboration.'),
    s('variables-outputs', 'Variables & Outputs', 'Input variables, validation, and output values.'),
    s('modules', 'Modules', 'Creating reusable modules and module composition.'),
    s('module-registry', 'Module Registry', 'Public modules, versioning, and private registries.'),
    s('workspaces', 'Workspaces', 'Environment separation with Terraform workspaces.'),
    s('plan-apply', 'Plan & Apply', 'terraform plan, apply, destroy, and targeted operations.'),
    s('import', 'Import Existing Resources', 'terraform import and bringing existing infra under management.'),
    s('count-for-each', 'count & for_each', 'Dynamic resource creation and iteration patterns.'),
    s('provisioners', 'Provisioners', 'local-exec, remote-exec, and when to avoid provisioners.'),
    s('testing-terraform', 'Testing Terraform', 'terraform validate, fmt, tflint, and terratest intro.'),
    s('ci-terraform', 'Terraform in CI/CD', 'Plan on PR, apply on merge, and drift detection.'),
    s('azurerm-patterns', 'Azure Resource Patterns', 'Resource groups, naming conventions, and tagging.'),
    s('networking-terraform', 'Networking with Terraform', 'VNets, subnets, NSGs, and peering in Terraform.'),
    s('security-terraform', 'Terraform Security', 'Secret management, state encryption, and policy as code.'),
    s('terraform-capstone', 'Terraform Capstone', 'Module-based Azure infrastructure deployment.'),
  ],

  monitoring: [
    s('monitor-overview', 'Azure Monitor Overview', 'Metrics, logs, traces, and the unified monitoring platform.'),
    s('metrics', 'Metrics', 'Metric namespaces, aggregation, and metric alerts.'),
    s('log-analytics', 'Log Analytics', 'Workspaces, data ingestion, and retention policies.'),
    s('kql-basics', 'KQL Basics', 'Query syntax, filters, projections, and summarize.'),
    s('kql-advanced', 'Advanced KQL', 'join, parse, makelist, and time-series analysis.'),
    s('application-insights', 'Application Insights', 'APM, dependency tracking, and request telemetry.'),
    s('alert-rules', 'Alert Rules', 'Metric alerts, log alerts, and alert processing rules.'),
    s('action-groups', 'Action Groups', 'Email, SMS, webhook, and ITSM integration notifications.'),
    s('dashboards', 'Dashboards', 'Azure Dashboards, workbooks, and Grafana integration.'),
    s('activity-log', 'Activity Log', 'Subscription-level events, audit trails, and export.'),
    s('diagnostic-settings', 'Diagnostic Settings', 'Resource log routing to Log Analytics and Storage.'),
    s('container-insights', 'Container Insights', 'AKS and container monitoring with Prometheus metrics.'),
    s('availability-tests', 'Availability Tests', 'URL ping tests and multi-location monitoring.'),
    s('smart-detection', 'Smart Detection', 'AI-powered anomaly detection in Application Insights.'),
    s('cost-monitoring', 'Monitoring Costs', 'Log Analytics ingestion costs and data collection rules.'),
    s('observability-patterns', 'Observability Patterns', 'Three pillars: metrics, logs, traces in Azure.'),
    s('monitoring-capstone', 'Monitoring Capstone', 'Set up alerts and dashboards for an Azure application.'),
  ],

  security: [
    s('security-overview', 'Azure Security Overview', 'Defense in depth, Zero Trust, and shared responsibility.'),
    s('entra-id', 'Microsoft Entra ID', 'Users, groups, conditional access, and MFA.'),
    s('rbac-deep', 'RBAC Deep Dive', 'Custom roles, deny assignments, and privilege management.'),
    s('managed-identities', 'Managed Identities', 'System-assigned vs user-assigned and token acquisition.'),
    s('key-vault', 'Azure Key Vault', 'Secrets, keys, certificates, and access policies.'),
    s('network-security', 'Network Security', 'NSGs, Azure Firewall, DDoS protection, and WAF.'),
    s('encryption', 'Encryption', 'Encryption at rest, in transit, and customer-managed keys.'),
    s('defender-cloud', 'Microsoft Defender for Cloud', 'Secure score, recommendations, and threat protection.'),
    s('sentinel-intro', 'Microsoft Sentinel Intro', 'SIEM, SOAR, and security analytics on Azure.'),
    s('devsecops', 'DevSecOps', 'Shift-left security, pipeline gates, and secure SDLC.'),
    s('sast-dast', 'SAST & DAST', 'Static and dynamic application security testing in CI/CD.'),
    s('secret-scanning', 'Secret Scanning', 'Detecting credentials in code and pipeline scanning tools.'),
    s('compliance', 'Compliance', 'Azure Policy, regulatory frameworks, and audit readiness.'),
    s('identity-governance', 'Identity Governance', 'PIM, access reviews, and entitlement management.'),
    s('incident-response', 'Incident Response', 'Security incident workflow and Azure-native tooling.'),
    s('security-capstone', 'Security Capstone', 'Design a secure Azure architecture with RBAC and Key Vault.'),
  ],
};

const AZURE_DATA_PATHS = {
  'azure-data-factory': [
    s('adf-overview', 'ADF Overview', 'Cloud ETL/ELT service, integration runtime, and pipeline concepts.'),
    s('linked-services', 'Linked Services', 'Connection strings, authentication, and supported connectors.'),
    s('datasets', 'Datasets', 'Dataset types, parameters, and schema definition.'),
    s('pipeline-basics', 'Pipeline Basics', 'Activities, dependencies, and pipeline runs.'),
    s('copy-activity', 'Copy Activity', 'Source-to-sink data movement, mapping, and performance.'),
    s('data-flows', 'Mapping Data Flows', 'Visual ETL transformations without coding.'),
    s('data-flow-transformations', 'Data Flow Transformations', 'Derived column, aggregate, join, and pivot in data flows.'),
    s('triggers-schedule', 'Schedule Triggers', 'Time-based pipeline execution and timezone handling.'),
    s('triggers-tumbling', 'Tumbling Window Triggers', 'Batch processing windows and dependency chains.'),
    s('triggers-event', 'Event Triggers', 'Blob events, custom events, and event-driven pipelines.'),
    s('parameters-variables', 'Parameters & Variables', 'Pipeline parameters, variables, and dynamic expressions.'),
    s('integration-runtime', 'Integration Runtime', 'Azure IR, self-hosted IR, and Azure-SSIS IR.'),
    s('self-hosted-ir', 'Self-Hosted IR', 'On-premises connectivity, HA setup, and troubleshooting.'),
    s('expressions', 'ADF Expressions', 'Dynamic content, functions, and pipeline logic.'),
    s('lookup-activity', 'Lookup Activity', 'Reference data retrieval and foreach loops.'),
    s('foreach-activity', 'ForEach Activity', 'Parallel iteration over arrays and batch processing.'),
    s('stored-procedure', 'Stored Procedure Activity', 'Executing SQL stored procedures from ADF.'),
    s('databricks-activity', 'Databricks Activity', 'Running notebooks and jobs from ADF pipelines.'),
    s('error-handling', 'Error Handling', 'Try-catch scopes, retry policies, and failure notifications.'),
    s('monitoring-adf', 'Monitoring ADF', 'Pipeline runs, alerts, and Azure Monitor integration.'),
    s('git-integration', 'Git Integration', 'Azure DevOps/GitHub integration and CI/CD for ADF.'),
    s('ci-cd-adf', 'CI/CD for ADF', 'ARM template export, publish branch, and automated deployment.'),
    s('performance-adf', 'ADF Performance', 'Parallel copies, DIU tuning, and partition options.'),
    s('security-adf', 'ADF Security', 'Managed identity, Key Vault, and private endpoints.'),
    s('cost-adf', 'ADF Cost Optimization', 'Pipeline efficiency, IR sizing, and activity optimization.'),
    s('delta-copy', 'Copy to Delta Lake', 'Landing data in Delta format from ADF copy activity.'),
    s('metadata-driven', 'Metadata-Driven Pipelines', 'Dynamic pipelines driven by configuration tables.'),
    s('adf-capstone', 'ADF Capstone', 'Build an end-to-end ingestion pipeline with triggers and monitoring.'),
  ],

  'azure-databricks': [
    s('databricks-overview', 'Databricks Overview', 'Unified analytics platform, workspace, and lakehouse vision.'),
    s('workspace-setup', 'Workspace Setup', 'Creating workspaces, admin settings, and user management.'),
    s('notebooks', 'Notebooks', 'Cells, magic commands, %sql, %sh, and version control.'),
    s('clusters-interactive', 'Interactive Clusters', 'Cluster modes, runtime versions, and autoscaling.'),
    s('clusters-job', 'Job Clusters', 'Ephemeral clusters for scheduled jobs and cost savings.'),
    s('dbfs', 'DBFS', 'Databricks File System, mount points, and cloud storage integration.'),
    s('delta-tables', 'Delta Tables in Databricks', 'Creating, reading, and managing Delta tables.'),
    s('sql-warehouse', 'SQL Warehouses', 'Serverless SQL, BI connectivity, and query performance.'),
    s('jobs-scheduling', 'Jobs & Scheduling', 'Job definitions, task dependencies, and retry policies.'),
    s('workflows', 'Databricks Workflows', 'Multi-task jobs, conditional tasks, and orchestration.'),
    s('unity-catalog', 'Unity Catalog', 'Three-level namespace, governance, and access control.'),
    s('secrets-scopes', 'Secrets Scopes', 'Key Vault-backed secrets and credential management.'),
    s('repos', 'Databricks Repos', 'Git integration, branch checkout, and CI/CD workflows.'),
    s('mlflow', 'MLflow on Databricks', 'Experiment tracking, model registry, and deployment.'),
    s('feature-store', 'Feature Store', 'Feature engineering, sharing, and online serving.'),
    s('streaming-databricks', 'Structured Streaming', 'Kafka, Event Hubs, and streaming on Databricks.'),
    s('photon-engine', 'Photon Engine', 'Vectorized query engine and performance benefits.'),
    s('cost-optimization', 'Cost Optimization', 'Cluster policies, spot instances, and auto-termination.'),
    s('security-databricks', 'Security', 'VPC injection, private link, and network isolation.'),
    s('monitoring-databricks', 'Monitoring', 'Cluster metrics, audit logs, and system tables.'),
    s('databricks-capstone', 'Databricks Capstone', 'Build a medallion pipeline with notebooks and jobs.'),
  ],

  'adls-gen2': [
    s('adls-overview', 'ADLS Gen2 Overview', 'Hierarchical namespace, Hadoop compatibility, and use cases.'),
    s('storage-account-setup', 'Storage Account Setup', 'Creating accounts, redundancy, and performance tiers.'),
    s('hierarchical-namespace', 'Hierarchical Namespace', 'Directories, ACLs, and POSIX-like semantics.'),
    s('access-control', 'Access Control', 'RBAC roles, ACLs, and access control best practices.'),
    s('authentication', 'Authentication Methods', 'Shared key, SAS, managed identity, and OAuth.'),
    s('data-lake-design', 'Data Lake Design', 'Zone layout, folder conventions, and naming standards.'),
    s('file-formats', 'File Formats', 'Parquet, Delta, CSV, JSON — choosing the right format.'),
    s('partitioning', 'Partitioning Strategy', 'Date, region, and entity-based partitioning patterns.'),
    s('performance-tuning', 'Performance Tuning', 'Parallel reads, block size, and small file problem.'),
    s('lifecycle-management', 'Lifecycle Management', 'Tiering policies, retention rules, and cost savings.'),
    s('private-endpoints', 'Private Endpoints', 'VNet integration and secure access without public internet.'),
    s('monitoring-adls', 'Monitoring ADLS', 'Metrics, diagnostic logs, and storage analytics.'),
    s('data-movement', 'Data Movement', 'AzCopy, ADF copy, and DistCp for large transfers.'),
    s('security-adls', 'Security Best Practices', 'Encryption, immutability, and soft delete.'),
    s('adls-capstone', 'ADLS Capstone', 'Design and implement a secure multi-zone data lake.'),
  ],

  'azure-sql-database': [
    s('azuresql-overview', 'Azure SQL Overview', 'PaaS SQL options: single database, elastic pool, managed instance.'),
    s('provisioning', 'Provisioning', 'Creating databases, tiers, and compute/storage sizing.'),
    s('connection', 'Connecting to Azure SQL', 'Connection strings, firewall rules, and private link.'),
    s('security-basics', 'Security Basics', 'Authentication, encryption TDE, and Always Encrypted.'),
    s('firewall-vnet', 'Firewall & VNet Rules', 'IP rules, service endpoints, and private endpoints.'),
    s('performance-tiers', 'Performance Tiers', 'DTU vs vCore models, serverless, and hyperscale.'),
    s('query-store', 'Query Store', 'Query performance tracking, plan regression, and tuning.'),
    s('indexing-azuresql', 'Indexing', 'Index design, missing index recommendations, and maintenance.'),
    s('elastic-pools', 'Elastic Pools', 'Multi-tenant resource sharing and eDTU management.'),
    s('geo-replication', 'Geo-Replication', 'Active geo-replication, failover groups, and DR planning.'),
    s('backup-restore', 'Backup & Restore', 'Automated backups, point-in-time restore, and LTR.'),
    s('migration-assessment', 'Migration Assessment', 'DMA, Azure Migrate, and compatibility assessment.'),
    s('migration-methods', 'Migration Methods', 'BACPAC, DMS, transaction replication, and cutover strategies.'),
    s('serverless', 'Serverless SQL', 'Auto-pause, auto-scale, and cost-effective dev/test workloads.'),
    s('synapse-link', 'Synapse Link', 'Near real-time analytics from Azure SQL to Synapse.'),
    s('monitoring-azuresql', 'Monitoring', 'Metrics, alerts, Intelligent Insights, and diagnostics.'),
    s('tuning-azuresql', 'Performance Tuning', 'Wait statistics, blocking, and query optimization.'),
    s('azuresql-capstone', 'Azure SQL Capstone', 'Provision, secure, and tune an Azure SQL database.'),
  ],

  'synapse-analytics': [
    s('synapse-overview', 'Synapse Overview', 'Unified analytics: SQL, Spark, pipelines, and studio.'),
    s('synapse-studio', 'Synapse Studio', 'Data hub, develop hub, monitor hub, and manage hub.'),
    s('dedicated-pools', 'Dedicated SQL Pools', 'MPP architecture, distributions, and table design.'),
    s('distribution-design', 'Distribution Design', 'Hash, round-robin, replicated tables, and skew.'),
    s('indexing-synapse', 'Indexing in Synapse', 'Clustered columnstore, heap, and index strategies.'),
    s('serverless-sql', 'Serverless SQL Pool', 'On-demand querying over data lake files with OPENROWSET.'),
    s('external-tables', 'External Tables', 'CETAS, external tables, and lakehouse querying patterns.'),
    s('spark-pools', 'Spark Pools', 'Synapse Spark, notebooks, and lakehouse processing.'),
    s('pipelines-synapse', 'Synapse Pipelines', 'Orchestration, data flows, and integration with ADF concepts.'),
    s('linked-services-synapse', 'Linked Services', 'Connecting to ADLS, SQL, and external data sources.'),
    s('security-synapse', 'Synapse Security', 'Workspace access, SQL permissions, and managed identity.'),
    s('monitoring-synapse', 'Monitoring Synapse', 'SQL requests, Spark jobs, and pipeline runs.'),
    s('performance-synapse', 'Performance Tuning', 'Workload management, resource classes, and caching.'),
    s('migration-synapse', 'Migration to Synapse', 'From SQL DW, on-prem, and other warehouses.'),
    s('synapse-capstone', 'Synapse Capstone', 'Build a lakehouse query pipeline with serverless and dedicated pools.'),
  ],

  'delta-lake': [
    s('delta-overview', 'Delta Lake Overview', 'Open format, ACID on data lakes, and the transaction log.'),
    s('delta-table-basics', 'Delta Table Basics', 'Creating, reading, and writing Delta tables in Spark.'),
    s('transaction-log', 'Transaction Log', 'JSON commit files, checkpointing, and log compaction.'),
    s('acid-transactions', 'ACID Transactions', 'Atomicity, consistency, isolation, and durability guarantees.'),
    s('schema-enforcement', 'Schema Enforcement', 'Schema on write, evolution, and mergeSchema option.'),
    s('time-travel', 'Time Travel', 'Version history, timestamp queries, and data recovery.'),
    s('merge-upsert', 'MERGE & Upsert', 'Delta MERGE syntax, SCD Type 2, and CDC patterns.'),
    s('optimize', 'OPTIMIZE', 'File compaction, bin-packing, and reducing small files.'),
    s('z-order', 'Z-Ordering', 'Multi-dimensional clustering for query performance.'),
    s('vacuum', 'VACUUM', 'Removing old files, retention policies, and storage cleanup.'),
    s('change-data-feed', 'Change Data Feed', 'CDC streams from Delta tables for downstream consumers.'),
    s('constraints', 'Delta Constraints', 'CHECK constraints and data quality enforcement.'),
    s('streaming-delta', 'Streaming & Delta', 'Structured Streaming sink and source with Delta Lake.'),
    s('unity-catalog-delta', 'Unity Catalog & Delta', 'Managed tables, sharing, and governance.'),
    s('performance-delta', 'Delta Performance', 'Statistics, data skipping, and query optimization.'),
    s('migration-delta', 'Migration to Delta', 'Converting Parquet/Hive tables to Delta format.'),
    s('delta-capstone', 'Delta Lake Capstone', 'Implement SCD Type 2 with MERGE and time travel.'),
  ],

  'pyspark-on-databricks': [
    s('intro-databricks-pyspark', 'PySpark on Databricks Intro', 'Why Databricks for PySpark and workspace advantages.'),
    s('notebook-pyspark', 'PySpark Notebooks', 'Running PySpark in Databricks notebooks with best practices.'),
    s('spark-session-databricks', 'SparkSession on Databricks', 'Pre-configured sessions, configs, and cluster attachment.'),
    s('reading-lake', 'Reading from Data Lake', 'ADLS paths, mount points, and cloud file access.'),
    s('delta-read-write', 'Delta Read & Write', 'Reading and writing Delta tables from PySpark.'),
    s('transformations-databricks', 'Transformations', 'DataFrame operations optimized for Databricks runtime.'),
    s('sql-databricks', 'Spark SQL on Databricks', '%sql magic, temp views, and SQL warehouses.'),
    s('udfs-databricks', 'UDFs on Databricks', 'Python UDFs, Pandas UDFs, and Vectorized UDFs.'),
    s('joins-databricks', 'Joins & Broadcast', 'Join optimization with AQE and broadcast hints.'),
    s('partitioning-databricks', 'Partitioning', 'Partition strategies for ADLS and Delta tables.'),
    s('streaming-databricks-pyspark', 'Structured Streaming', 'Kafka/Event Hubs streaming with PySpark on Databricks.'),
    s('jobs-pyspark', 'Jobs with PySpark', 'Packaging notebooks as jobs and scheduling.'),
    s('testing-databricks', 'Testing PySpark Jobs', 'Unit testing patterns and dbutils in tests.'),
    s('performance-databricks', 'Performance Tuning', 'Spark UI, Photon, and adaptive query execution.'),
    s('architecture', 'Spark Architecture Deep Dive', 'Cluster architecture, scheduling, shuffle, and Catalyst.', { href: 'blog/spark-architecture.html' }),
    s('monitoring-jobs', 'Monitoring Jobs', 'Job runs, cluster metrics, and alerting.'),
    s('best-practices-databricks', 'Best Practices', 'Notebook organization, repos, and production patterns.'),
    s('capstone-databricks', 'Databricks PySpark Capstone', 'End-to-end batch pipeline on Databricks.'),
  ],

  'medallion-architecture': [
    s('medallion-overview', 'Medallion Overview', 'Bronze-Silver-Gold layers and the lakehouse pattern.'),
    s('bronze-layer', 'Bronze Layer', 'Raw ingestion, landing zones, and immutable source copies.'),
    s('bronze-patterns', 'Bronze Ingestion Patterns', 'Full load, incremental, CDC, and streaming ingestion.'),
    s('silver-layer', 'Silver Layer', 'Cleansed, conformed, deduplicated, and typed data.'),
    s('silver-transformations', 'Silver Transformations', 'Data quality rules, standardization, and enrichment.'),
    s('gold-layer', 'Gold Layer', 'Business aggregates, KPIs, and serving-layer tables.'),
    s('gold-modeling', 'Gold Data Modeling', 'Star schema, wide tables, and semantic layer design.'),
    s('delta-medallion', 'Delta Lake in Medallion', 'ACID guarantees across layers and MERGE for CDC.'),
    s('unity-catalog-medallion', 'Unity Catalog Governance', 'Catalog structure, permissions, and lineage across layers.'),
    s('streaming-medallion', 'Streaming Medallion', 'Real-time bronze-to-gold with Structured Streaming.'),
    s('testing-medallion', 'Testing Medallion Pipelines', 'Data quality checks, Great Expectations, and assertions.'),
    s('monitoring-medallion', 'Monitoring & Lineage', 'Pipeline observability and data lineage tracking.'),
    s('migration-medallion', 'Migration to Medallion', 'Transitioning from legacy warehouses to medallion.'),
    s('cost-medallion', 'Cost Optimization', 'Storage tiering, compaction, and compute efficiency per layer.'),
    s('medallion-capstone', 'Medallion Capstone', 'Implement bronze-silver-gold on Azure Databricks.'),
  ],

  'data-pipeline-projects': [
    s('pipeline-design', 'Pipeline Design Principles', 'Requirements gathering, SLAs, and architecture decisions.'),
    s('batch-etl', 'Batch ETL Pipeline', 'Designing batch ETL with ADF and Databricks.'),
    s('incremental-load', 'Incremental Load Patterns', 'Watermark columns, change tracking, and MERGE.'),
    s('streaming-pipeline', 'Streaming Pipeline', 'Real-time ingestion with Event Hubs and Spark Streaming.'),
    s('lambda-architecture', 'Lambda Architecture', 'Batch and speed layers for hybrid processing.'),
    s('kappa-architecture', 'Kappa Architecture', 'Stream-only processing with replay capability.'),
    s('data-quality', 'Data Quality Framework', 'Validation rules, quarantine zones, and alerting.'),
    s('orchestration', 'Pipeline Orchestration', 'ADF triggers, Databricks workflows, and dependency management.'),
    s('error-handling-projects', 'Error Handling', 'Dead letter queues, retry logic, and failure notifications.'),
    s('monitoring-projects', 'Monitoring & Alerting', 'Pipeline health dashboards and SLA monitoring.'),
    s('security-projects', 'Security in Pipelines', 'Managed identity, encryption, and access control.'),
    s('cost-projects', 'Cost Management', 'Right-sizing, scheduling, and storage optimization.'),
    s('testing-pipelines', 'Testing Pipelines', 'Integration tests, data reconciliation, and smoke tests.'),
    s('ci-cd-pipelines', 'CI/CD for Pipelines', 'Automated deployment of ADF and Databricks artifacts.'),
    s('documentation', 'Documentation & Lineage', 'Data dictionaries, pipeline docs, and lineage tools.'),
    s('retail-project', 'Project: Retail Analytics', 'End-to-end retail data pipeline from POS to dashboards.'),
    s('iot-project', 'Project: IoT Telemetry', 'Streaming IoT data ingestion and real-time analytics.'),
    s('finance-project', 'Project: Financial Reporting', 'Regulatory reporting pipeline with audit trails.'),
    s('healthcare-project', 'Project: Healthcare Data', 'HIPAA-aware pipeline with PHI handling patterns.'),
    s('migration-project', 'Project: Legacy Migration', 'On-premises to Azure cloud migration pipeline.'),
    s('capstone-project', 'Capstone: Full Pipeline', 'Design, build, and document a production-grade data pipeline.'),
  ],
};

module.exports = { AZURE_DEVOPS_PATHS, AZURE_DATA_PATHS, s };
