/**
 * Interview Questions learning paths — Q&A format steps
 */
function s(slug, label, description, extra = {}) {
  return { slug, label, description, ...extra };
}

const INTERVIEW_PATHS = {
  'python-interview-questions': [
    s('basics-syntax', 'Basics & Syntax', 'Core Python syntax, indentation, and fundamental language rules.'),
    s('data-structures', 'Data Structures', 'Lists, tuples, dicts, sets — operations and time complexity.'),
    s('strings-interview', 'Strings', 'String manipulation, formatting, and common string interview questions.'),
    s('functions-interview', 'Functions', 'Parameters, scope, closures, and first-class functions.'),
    s('oop-interview', 'OOP Concepts', 'Classes, inheritance, MRO, and magic methods.'),
    s('decorators-interview', 'Decorators', 'Decorator syntax, use cases, and implementation questions.'),
    s('generators-interview', 'Generators & Iterators', 'yield, iter protocol, and lazy evaluation.'),
    s('comprehensions-interview', 'Comprehensions', 'List/dict/set comprehensions and generator expressions.'),
    s('exceptions-interview', 'Exception Handling', 'try/except patterns and custom exception design.'),
    s('modules-interview', 'Modules & Packages', 'Import system, __name__, and package structure.'),
    s('memory-management', 'Memory Management', 'Reference counting, garbage collection, and __slots__.'),
    s('gIL-threading', 'GIL & Threading', 'Global Interpreter Lock, threading vs multiprocessing.'),
    s('multiprocessing', 'Multiprocessing', 'Process pools, shared memory, and parallel execution.'),
    s('async-interview', 'Async & Concurrency', 'asyncio, coroutines, and async interview scenarios.'),
    s('file-io-interview', 'File I/O', 'Reading/writing files, context managers, and pathlib.'),
    s('testing-interview', 'Testing', 'unittest, pytest, mocking, and test design questions.'),
    s('algorithms-python', 'Algorithms in Python', 'Sorting, searching, and common algorithm implementations.'),
    s('coding-patterns', 'Coding Patterns', 'Two pointers, sliding window, and hash map patterns.'),
    s('scenario-debugging', 'Scenario: Debugging', 'Debugging production issues and reading tracebacks.'),
    s('scenario-system-design', 'Scenario: System Design', 'Designing Python services and API backends.'),
  ],

  'sql-interview-questions': [
    s('basics-select', 'SELECT Fundamentals', 'Basic queries, filtering, sorting, and aggregation questions.'),
    s('joins-interview', 'JOINs', 'All join types with practical business scenario questions.'),
    s('subqueries-interview', 'Subqueries', 'Nested queries, EXISTS, and IN vs JOIN trade-offs.'),
    s('aggregates-interview', 'Aggregates & GROUP BY', 'Aggregation patterns and HAVING clause questions.'),
    s('window-interview', 'Window Functions', 'ROW_NUMBER, RANK, LAG/LEAD interview scenarios.'),
    s('ctes-interview', 'CTEs & Recursive Queries', 'WITH clauses and hierarchical data queries.'),
    s('indexing-interview', 'Indexing', 'Index types, when to index, and index interview questions.'),
    s('normalization-interview', 'Normalization', 'Normal forms, denormalization, and schema design.'),
    s('transactions-interview', 'Transactions & ACID', 'Isolation levels, deadlocks, and concurrency.'),
    s('performance-interview', 'Query Performance', 'Execution plans, optimization, and slow query diagnosis.'),
    s('data-modeling', 'Data Modeling', 'Star schema, snowflake, and dimensional modeling questions.'),
    s('analytical-patterns', 'Analytical SQL Patterns', 'Running totals, top-N, gaps, and pivots.'),
    s('stored-procs-interview', 'Stored Procedures', 'Procedures vs functions and server-side logic.'),
    s('scenario-reporting', 'Scenario: Reporting', 'Building reports and dashboards with SQL.'),
    s('scenario-etl', 'Scenario: ETL Design', 'Staging, transformation, and load pattern questions.'),
    s('scenario-debugging', 'Scenario: Query Debugging', 'Diagnosing incorrect results and data issues.'),
    s('dialect-differences', 'SQL Dialect Differences', 'T-SQL, PostgreSQL, and ANSI SQL variations.'),
    s('advanced-optimization', 'Advanced Optimization', 'Partitioning, materialized views, and query hints.'),
    s('scenario-analytics', 'Scenario: Business Analytics', 'Revenue, cohort, and funnel analysis questions.'),
    s('scenario-system-design', 'Scenario: Database Design', 'Designing schemas for e-commerce and SaaS apps.'),
  ],

  'pyspark-interview-questions': [
    s('spark-fundamentals', 'Spark Fundamentals', 'RDD vs DataFrame, lazy evaluation, and Spark architecture basics.'),
    s('transformations-interview', 'Transformations', 'map, filter, join transformations and lineage questions.'),
    s('actions-interview', 'Actions', 'collect, count, save — when actions trigger jobs.'),
    s('dataframes-interview', 'DataFrames', 'Schema, columns, and DataFrame API interview questions.'),
    s('spark-sql-interview', 'Spark SQL', 'Temp views, spark.sql(), and Catalyst optimizer questions.'),
    s('joins-spark', 'Joins in Spark', 'Join types, broadcast joins, and sort-merge join mechanics.'),
    s('partitioning-interview', 'Partitioning', 'repartition, coalesce, and partition pruning questions.'),
    s('caching-interview', 'Caching & Persistence', 'cache vs persist, storage levels, and when to cache.'),
    s('udfs-interview', 'UDFs', 'Python UDFs, Pandas UDFs, and performance implications.'),
    s('shuffle-interview', 'Shuffle Operations', 'What causes shuffle, wide vs narrow transformations.'),
    s('performance-interview', 'Performance Tuning', 'Spark UI, stages, skew, and configuration tuning.'),
    s('streaming-interview', 'Structured Streaming', 'Streaming concepts, watermarks, and output modes.'),
    s('architecture-interview', 'Architecture Deep Dive', 'Driver, executors, DAG scheduler, and task execution.', { href: 'blog/spark-architecture.html' }),
    s('delta-interview', 'Delta Lake Questions', 'ACID, time travel, MERGE, and Delta-specific scenarios.'),
    s('scenario-large-scale', 'Scenario: Large-Scale ETL', 'Processing terabytes — design and optimization questions.'),
    s('scenario-debugging', 'Scenario: Job Failures', 'OOM errors, skew, and troubleshooting Spark jobs.'),
    s('scenario-optimization', 'Scenario: Optimization', 'Reducing shuffle, broadcast decisions, and AQE.'),
    s('scenario-streaming', 'Scenario: Streaming Pipeline', 'Designing real-time processing pipelines.'),
    s('databricks-interview', 'Databricks-Specific', 'Clusters, notebooks, Unity Catalog interview topics.'),
    s('scenario-system-design', 'Scenario: System Design', 'Designing a data platform with Spark at scale.'),
  ],

  'azure-devops-interview-questions': [
    s('devops-fundamentals', 'DevOps Fundamentals', 'CI/CD concepts, DevOps culture, and Azure DevOps services overview.'),
    s('git-interview', 'Git & Version Control', 'Branching, merging, rebasing, and Git workflow questions.'),
    s('azure-repos-interview', 'Azure Repos', 'PR workflows, branch policies, and code review practices.'),
    s('yaml-pipelines-interview', 'YAML Pipelines', 'Pipeline structure, triggers, and YAML syntax questions.'),
    s('ci-interview', 'Continuous Integration', 'Build automation, test gates, and CI best practices.'),
    s('cd-interview', 'Continuous Deployment', 'Release strategies, environments, and deployment gates.'),
    s('docker-interview', 'Docker Questions', 'Images, containers, Dockerfile, and container interview topics.'),
    s('kubernetes-interview', 'Kubernetes Questions', 'Pods, services, deployments, and K8s architecture.'),
    s('aks-interview', 'AKS Questions', 'Managed Kubernetes, scaling, and Azure-specific K8s topics.'),
    s('terraform-interview', 'Terraform Questions', 'State management, modules, and IaC interview scenarios.'),
    s('monitoring-interview', 'Monitoring & Alerting', 'Azure Monitor, KQL, and observability questions.'),
    s('security-interview', 'Security & DevSecOps', 'RBAC, Key Vault, SAST/DAST, and pipeline security.'),
    s('scenario-incident', 'Scenario: Incident Response', 'Production outage response and rollback procedures.'),
    s('scenario-pipeline-design', 'Scenario: Pipeline Design', 'Designing CI/CD for microservices architecture.'),
    s('scenario-migration', 'Scenario: Cloud Migration', 'Migrating on-prem workloads to Azure with DevOps.'),
    s('scenario-branching', 'Scenario: Branching Strategy', 'Choosing and implementing branching models.'),
    s('scenario-iac', 'Scenario: Infrastructure as Code', 'Terraform/Bicep deployment pipeline design.'),
    s('scenario-compliance', 'Scenario: Compliance', 'Audit trails, approval gates, and regulatory requirements.'),
    s('scenario-cost', 'Scenario: Cost Optimization', 'Right-sizing agents, caching, and pipeline efficiency.'),
    s('scenario-leadership', 'Scenario: DevOps Leadership', 'Team transformation and DevOps maturity assessment.'),
  ],

  'azure-data-engineering-interview-questions': [
    s('de-fundamentals', 'Data Engineering Fundamentals', 'ETL vs ELT, batch vs streaming, and data pipeline concepts.'),
    s('adf-interview', 'Azure Data Factory', 'Pipelines, linked services, triggers, and ADF interview questions.'),
    s('databricks-interview', 'Azure Databricks', 'Workspace, clusters, notebooks, and Databricks scenarios.'),
    s('adls-interview', 'ADLS Gen2', 'Data lake design, ACLs, and storage interview questions.'),
    s('delta-lake-interview', 'Delta Lake', 'ACID, time travel, MERGE, and Delta-specific interview topics.'),
    s('synapse-interview', 'Synapse Analytics', 'Dedicated vs serverless pools and Synapse architecture.'),
    s('medallion-interview', 'Medallion Architecture', 'Bronze-silver-gold layers and implementation questions.'),
    s('pyspark-de-interview', 'PySpark for DE', 'DataFrame operations, joins, and Spark performance for DE roles.'),
    s('sql-de-interview', 'SQL for Data Engineering', 'Analytical SQL, window functions, and warehouse queries.'),
    s('streaming-de-interview', 'Streaming Pipelines', 'Event Hubs, Kafka, Structured Streaming interview topics.'),
    s('data-modeling-interview', 'Data Modeling', 'Dimensional modeling, star schema, and lakehouse design.'),
    s('data-quality-interview', 'Data Quality', 'Validation, monitoring, and data quality framework questions.'),
    s('scenario-etl-design', 'Scenario: ETL Design', 'Design end-to-end batch pipeline for business requirements.'),
    s('scenario-streaming', 'Scenario: Real-Time Pipeline', 'Design streaming architecture for IoT or clickstream data.'),
    s('scenario-migration-de', 'Scenario: Migration', 'Migrating on-prem data warehouse to Azure lakehouse.'),
    s('scenario-performance', 'Scenario: Performance', 'Optimizing slow pipelines and reducing costs.'),
    s('scenario-governance', 'Scenario: Data Governance', 'Unity Catalog, lineage, and compliance requirements.'),
    s('scenario-scd', 'Scenario: SCD Implementation', 'Slowly changing dimensions with Delta MERGE.'),
    s('scenario-incident-de', 'Scenario: Pipeline Failure', 'Debugging failed pipelines and data reconciliation.'),
    s('scenario-system-design-de', 'Scenario: Platform Design', 'Designing enterprise data platform on Azure.'),
  ],

  'ai-ml-interview-questions': [
    s('ml-fundamentals-interview', 'ML Fundamentals', 'Supervised vs unsupervised, bias-variance, and ML lifecycle.'),
    s('algorithms-interview', 'Algorithms', 'When to use regression, trees, SVM, and ensemble methods.'),
    s('evaluation-interview', 'Model Evaluation', 'Metrics, cross-validation, and model selection questions.'),
    s('feature-engineering-interview', 'Feature Engineering', 'Encoding, scaling, selection, and pipeline design.'),
    s('deep-learning-interview', 'Deep Learning Basics', 'Neural networks, backprop, and activation functions.'),
    s('cnn-interview', 'CNN Questions', 'Convolution, pooling, and image classification interview topics.'),
    s('rnn-interview', 'RNN & LSTM', 'Sequence models, vanishing gradients, and LSTM gates.'),
    s('transformers-interview', 'Transformers & LLMs', 'Attention, BERT, GPT, and transformer architecture questions.'),
    s('nlp-interview', 'NLP Questions', 'Tokenization, embeddings, and text classification scenarios.'),
    s('genai-interview', 'Generative AI', 'Prompt engineering, RAG, fine-tuning, and LLM deployment.'),
    s('mlops-interview', 'MLOps', 'Model versioning, deployment, monitoring, and experiment tracking.'),
    s('statistics-interview', 'Statistics for ML', 'Distributions, hypothesis testing, and A/B test design.'),
    s('scenario-classification', 'Scenario: Classification', 'Design a fraud detection or churn prediction system.'),
    s('scenario-nlp', 'Scenario: NLP System', 'Build a sentiment analysis or chatbot system design.'),
    s('scenario-recommendation', 'Scenario: Recommendations', 'Design a recommendation engine architecture.'),
    s('scenario-llm', 'Scenario: LLM Application', 'Design a RAG system or fine-tuned assistant.'),
    s('scenario-evaluation', 'Scenario: Model Evaluation', 'Choosing metrics and handling imbalanced data.'),
    s('scenario-production', 'Scenario: Production ML', 'Deploying models at scale with monitoring.'),
    s('scenario-ethics', 'Scenario: AI Ethics', 'Bias, fairness, and responsible AI interview questions.'),
    s('scenario-system-design-ml', 'Scenario: ML System Design', 'End-to-end ML platform architecture design.'),
  ],
};

module.exports = { INTERVIEW_PATHS, s };
