/**
 * Learning path step definitions for all submenu topics.
 * Each entry: { slug, label, description, codeLang?, noCode?, href? }
 */
function s(slug, label, description, extra = {}) {
  return { slug, label, description, ...extra };
}

const PATHS = {
  python: [
    s('getting-started', 'Getting Started with Python', 'Why Python matters for data engineering, automation, and backend development.'),
    s('installation-setup', 'Installation & Setup', 'Installing Python, choosing an editor, and running your first script.'),
    s('variables', 'Variables & Assignment', 'Naming variables, assignment rules, and dynamic typing in Python.'),
    s('data-types-overview', 'Data Types Overview', 'Numbers, strings, booleans, and type checking with type().'),
    s('numbers-math', 'Numbers & Math', 'Integers, floats, arithmetic operators, and math module basics.'),
    s('strings', 'Strings', 'String creation, slicing, formatting, and common string methods.'),
    s('lists', 'Lists', 'Mutable sequences, indexing, slicing, and list methods.'),
    s('tuples', 'Tuples', 'Immutable sequences, packing/unpacking, and when to use tuples.'),
    s('sets', 'Sets', 'Unique collections, set operations, and membership testing.'),
    s('dictionaries', 'Dictionaries', 'Key-value mappings, dict methods, and nested structures.'),
    s('operators', 'Operators', 'Arithmetic, comparison, logical, and assignment operators.'),
    s('control-flow-if', 'If Statements', 'Conditional logic with if, elif, else, and truthiness.'),
    s('loops', 'Loops', 'for and while loops, break, continue, and loop patterns.'),
    s('functions-basics', 'Functions Basics', 'Defining functions, calling functions, and docstrings.'),
    s('function-parameters', 'Function Parameters', 'Positional, keyword, default, *args, and **kwargs.'),
    s('scope-closures', 'Scope & Closures', 'Local vs global scope, LEGB rule, and closure patterns.'),
    s('comprehensions', 'Comprehensions', 'List, dict, and set comprehensions for concise transformations.'),
    s('file-io', 'File I/O', 'Reading and writing text files with open() and pathlib.'),
    s('exceptions', 'Exception Handling', 'try/except/else/finally, raising exceptions, and custom errors.'),
    s('modules-imports', 'Modules & Imports', 'Import statements, packages, __name__, and project structure.'),
    s('oop-classes', 'Classes & Objects', 'Defining classes, __init__, instance attributes, and methods.'),
    s('oop-inheritance', 'Inheritance & Polymorphism', 'Subclassing, method overriding, and super().'),
    s('decorators', 'Decorators', 'Function decorators, functools.wraps, and practical decorator patterns.'),
    s('generators', 'Generators', 'yield keyword, generator expressions, and lazy iteration.'),
    s('context-managers', 'Context Managers', 'with statements, contextlib, and resource management.'),
    s('virtual-environments', 'Virtual Environments', 'venv, conda, and isolating project dependencies.'),
    s('pip-packaging', 'pip & Packaging', 'Installing packages, requirements.txt, and pyproject.toml basics.'),
    s('numpy-intro', 'NumPy Introduction', 'ndarrays, vectorization, and numerical computing fundamentals.'),
    s('pandas-intro', 'Pandas Introduction', 'DataFrames, Series, and essential data manipulation.'),
    s('asyncio', 'Asyncio Basics', 'async/await, event loops, and concurrent I/O patterns.'),
    s('testing', 'Testing with pytest', 'Writing tests, fixtures, parametrize, and TDD workflows.'),
    s('type-hints', 'Type Hints', 'Annotations, typing module, and static analysis with mypy.'),
    s('logging', 'Logging', 'logging module, log levels, handlers, and production logging patterns.'),
    s('best-practices', 'Best Practices', 'PEP 8, clean code, and production-ready Python habits.'),
    s('capstone', 'Capstone Project', 'Build a small CLI or data script combining concepts from this path.'),
  ],

  sql: [
    s('introduction', 'Introduction to SQL', 'Relational databases, SQL dialects, and the query execution model.'),
    s('select-basics', 'SELECT Basics', 'Retrieving columns and rows from tables with SELECT.'),
    s('where-filtering', 'WHERE & Filtering', 'Filtering rows with comparison, IN, BETWEEN, and LIKE.'),
    s('sorting-limit', 'ORDER BY & LIMIT', 'Sorting results and limiting row counts.'),
    s('aggregates', 'Aggregate Functions', 'COUNT, SUM, AVG, MIN, MAX, and NULL handling.'),
    s('group-by', 'GROUP BY & HAVING', 'Grouping rows and filtering aggregated results.'),
    s('joins-inner', 'INNER JOIN', 'Combining tables on matching keys with INNER JOIN.'),
    s('joins-outer', 'OUTER JOINs', 'LEFT, RIGHT, and FULL outer joins for incomplete matches.'),
    s('joins-cross', 'CROSS JOIN & Self Join', 'Cartesian products and joining a table to itself.'),
    s('subqueries', 'Subqueries', 'Nested SELECT statements in WHERE, FROM, and SELECT clauses.'),
    s('correlated-subqueries', 'Correlated Subqueries', 'Subqueries that reference outer query columns.'),
    s('ctes', 'Common Table Expressions', 'WITH clauses for readable, modular query design.'),
    s('window-functions-intro', 'Window Functions Intro', 'OVER clause, PARTITION BY, and ROW_NUMBER.'),
    s('window-ranking', 'Ranking Functions', 'RANK, DENSE_RANK, and NTILE for ordered analytics.'),
    s('window-offset', 'LAG & LEAD', 'Accessing previous and next row values in result sets.'),
    s('data-types', 'SQL Data Types', 'Numeric, string, date/time, and JSON types across dialects.'),
    s('constraints', 'Constraints', 'PRIMARY KEY, FOREIGN KEY, UNIQUE, CHECK, and NOT NULL.'),
    s('normalization', 'Normalization', '1NF through 3NF, denormalization trade-offs, and schema design.'),
    s('indexes', 'Indexes', 'B-tree indexes, composite indexes, and covering indexes.'),
    s('views', 'Views', 'Virtual tables, updatable views, and security through views.'),
    s('stored-procedures', 'Stored Procedures', 'Server-side procedures, functions, and parameters.'),
    s('transactions', 'Transactions & ACID', 'BEGIN, COMMIT, ROLLBACK, and isolation levels.'),
    s('query-plans', 'Query Execution Plans', 'Reading EXPLAIN output and identifying bottlenecks.'),
    s('performance-tuning', 'Performance Tuning', 'Statistics, index selection, and query rewriting.'),
    s('temp-tables', 'Temporary Tables', 'Session temp tables, table variables, and staging patterns.'),
    s('pivot-unpivot', 'PIVOT & UNPIVOT', 'Transforming rows to columns and back for reporting.'),
    s('json-sql', 'JSON in SQL', 'JSON columns, extraction operators, and semi-structured data.'),
    s('merge-upsert', 'MERGE / Upsert', 'INSERT ON CONFLICT, MERGE statements, and SCD patterns.'),
    s('security', 'SQL Security', 'SQL injection prevention, grants, roles, and row-level security.'),
    s('interview-patterns', 'Analytical SQL Patterns', 'Running totals, top-N per group, and gap detection.'),
  ],

  pyspark: [
    s('introduction', 'Introduction to PySpark', 'Distributed computing, Spark ecosystem, and when to use Spark.'),
    s('spark-session', 'SparkSession Setup', 'Creating SparkSession, configs, and local vs cluster modes.'),
    s('rdd-basics', 'RDD Basics', 'Resilient Distributed Datasets — Spark\'s foundational abstraction.'),
    s('rdd-transformations', 'RDD Transformations', 'map, filter, flatMap, and lazy evaluation on RDDs.'),
    s('rdd-actions', 'RDD Actions', 'collect, count, reduce, and triggering job execution.'),
    s('dataframes-intro', 'DataFrames Introduction', 'Structured data, schemas, and Spark SQL integration.'),
    s('reading-data', 'Reading Data', 'CSV, JSON, Parquet, and JDBC sources with options.'),
    s('writing-data', 'Writing Data', 'Save modes, partitioning on write, and file formats.'),
    s('select-filter', 'Select & Filter', 'Column selection, where clauses, and column expressions.'),
    s('aggregations', 'Aggregations', 'groupBy, agg, pivot, and rollup/cube operations.'),
    s('joins', 'DataFrame Joins', 'Join types, broadcast hints, and join optimization.'),
    s('transformations-lazy', 'Lazy Transformations', 'Transformation lineage, DAG, and catalyst involvement.'),
    s('actions-eager', 'Eager Actions', 'show, count, collect, and understanding job triggers.'),
    s('spark-sql', 'Spark SQL', 'spark.sql(), temp views, and global temp views.'),
    s('udfs', 'User-Defined Functions', 'Python UDFs, Pandas UDFs, and performance trade-offs.'),
    s('partitioning', 'Partitioning', 'repartition, coalesce, partition pruning, and shuffle impact.'),
    s('caching', 'Caching & Persistence', 'cache, persist, storage levels, and memory management.'),
    s('broadcast-joins', 'Broadcast Joins', 'When to broadcast, spark.sql.autoBroadcastJoinThreshold.'),
    s('handling-skew', 'Handling Data Skew', 'Salting, AQE skew join, and repartition strategies.'),
    s('window-functions', 'Window Functions', 'Window specs, ranking, and analytic functions in Spark.'),
    s('streaming-intro', 'Structured Streaming Intro', 'Streaming DataFrames, triggers, and output modes.'),
    s('watermarks', 'Watermarks & Late Data', 'Event-time processing and stateful aggregations.'),
    s('performance-tuning', 'Performance Tuning', 'Spark UI, stages, tasks, and configuration knobs.'),
    s('spark-config', 'Spark Configuration', 'executor memory, cores, shuffle partitions, and AQE.'),
    s('error-debugging', 'Debugging Spark Jobs', 'Reading logs, common exceptions, and troubleshooting.'),
    s('testing-pyspark', 'Testing PySpark', 'Local testing, chispa, and unit test patterns.'),
    s('delta-intro', 'Delta Lake Intro', 'ACID tables, time travel, and merge operations overview.'),
    s('production-patterns', 'Production Patterns', 'Job scheduling, monitoring, and deployment on clusters.'),
    s('architecture', 'Spark Architecture Deep Dive', 'Cluster architecture, scheduling, shuffle, and Catalyst optimizer.', { href: 'blog/spark-architecture.html' }),
    s('best-practices', 'PySpark Best Practices', 'Code organization, avoiding UDFs, and performance habits.'),
    s('capstone-etl', 'Capstone ETL Job', 'End-to-end batch pipeline design with PySpark.'),
  ],

  'data-science': [
    s('what-is-data-science', 'What is Data Science?', 'The data science lifecycle, roles, and core competencies.'),
    s('data-types-sources', 'Data Types & Sources', 'Structured, semi-structured, unstructured data and acquisition.'),
    s('python-for-ds', 'Python for Data Science', 'NumPy, pandas, matplotlib ecosystem overview.'),
    s('jupyter-workflows', 'Jupyter Workflows', 'Notebooks, reproducibility, and collaborative analysis.'),
    s('descriptive-stats', 'Descriptive Statistics', 'Mean, median, mode, variance, and distribution shapes.'),
    s('probability-basics', 'Probability Basics', 'Conditional probability, Bayes theorem, and random variables.'),
    s('distributions', 'Statistical Distributions', 'Normal, binomial, Poisson, and when each applies.'),
    s('hypothesis-testing', 'Hypothesis Testing', 'p-values, t-tests, chi-square, and significance levels.'),
    s('correlation', 'Correlation & Covariance', 'Pearson, Spearman, and interpreting relationships.'),
    s('data-cleaning', 'Data Cleaning', 'Missing values, outliers, duplicates, and imputation strategies.'),
    s('feature-exploration', 'Feature Exploration', 'Univariate and bivariate analysis techniques.'),
    s('visualization-basics', 'Visualization Basics', 'Bar, line, scatter, histogram charts with matplotlib/seaborn.'),
    s('visualization-advanced', 'Advanced Visualization', 'Heatmaps, pair plots, and storytelling with data.'),
    s('eda-workflow', 'EDA Workflow', 'Systematic exploratory data analysis from raw to insights.'),
    s('sampling', 'Sampling Methods', 'Random, stratified, bootstrap, and sampling bias.'),
    s('ab-testing', 'A/B Testing', 'Experiment design, metrics, and statistical analysis of experiments.'),
    s('time-series-intro', 'Time Series Intro', 'Trends, seasonality, and basic time series decomposition.'),
    s('sql-for-analysts', 'SQL for Analysts', 'Analytical queries analysts use daily in warehouses.'),
    s('communication', 'Communicating Insights', 'Reports, dashboards, and stakeholder presentations.'),
    s('ethics-bias', 'Ethics & Bias', 'Fairness, privacy, and responsible data practices.'),
    s('tools-ecosystem', 'Tools Ecosystem', 'pandas, scikit-learn, SQL, and cloud notebook platforms.'),
    s('case-study-retail', 'Case Study: Retail Analytics', 'End-to-end analysis of sales and customer data.'),
    s('case-study-churn', 'Case Study: Churn Analysis', 'Identifying at-risk customers with EDA and modeling prep.'),
    s('portfolio-projects', 'Portfolio Projects', 'Building a data science portfolio that gets interviews.'),
    s('career-path', 'Career Path', 'Junior to senior data scientist skills and certifications.'),
  ],

  'machine-learning': [
    s('ml-overview', 'Machine Learning Overview', 'Supervised, unsupervised, reinforcement learning paradigms.'),
    s('scikit-learn-setup', 'scikit-learn Setup', 'Installation, API conventions, and estimator interface.'),
    s('train-test-split', 'Train/Test Split', 'Holdout validation, random_state, and data leakage prevention.'),
    s('linear-regression', 'Linear Regression', 'Ordinary least squares, coefficients, and R-squared.'),
    s('logistic-regression', 'Logistic Regression', 'Binary classification, sigmoid, and decision boundaries.'),
    s('knn', 'K-Nearest Neighbors', 'Instance-based learning, distance metrics, and k selection.'),
    s('decision-trees', 'Decision Trees', 'Splitting criteria, tree depth, and interpretability.'),
    s('random-forest', 'Random Forest', 'Ensemble bagging, feature importance, and out-of-bag error.'),
    s('gradient-boosting', 'Gradient Boosting', 'XGBoost, LightGBM concepts, and boosting vs bagging.'),
    s('svm', 'Support Vector Machines', 'Margins, kernels, and when SVMs excel.'),
    s('naive-bayes', 'Naive Bayes', 'Probabilistic classification for text and categorical data.'),
    s('clustering-kmeans', 'K-Means Clustering', 'Centroids, elbow method, and cluster evaluation.'),
    s('clustering-hierarchical', 'Hierarchical Clustering', 'Agglomerative clustering and dendrograms.'),
    s('pca', 'PCA & Dimensionality Reduction', 'Principal components, variance explained, and t-SNE intro.'),
    s('feature-engineering', 'Feature Engineering', 'Encoding, scaling, binning, and domain features.'),
    s('pipelines', 'ML Pipelines', 'ColumnTransformer, Pipeline, and reproducible preprocessing.'),
    s('cross-validation', 'Cross-Validation', 'K-fold, stratified CV, and nested cross-validation.'),
    s('classification-metrics', 'Classification Metrics', 'Accuracy, precision, recall, F1, ROC-AUC.'),
    s('regression-metrics', 'Regression Metrics', 'MSE, RMSE, MAE, and R-squared interpretation.'),
    s('imbalanced-data', 'Imbalanced Data', 'SMOTE, class weights, and threshold tuning.'),
    s('hyperparameter-tuning', 'Hyperparameter Tuning', 'Grid search, random search, and Optuna intro.'),
    s('model-selection', 'Model Selection', 'Bias-variance tradeoff and choosing the right algorithm.'),
    s('overfitting', 'Overfitting & Regularization', 'L1/L2 regularization, dropout concept, and early stopping.'),
    s('feature-selection', 'Feature Selection', 'Filter, wrapper, and embedded selection methods.'),
    s('mlops-intro', 'MLOps Introduction', 'Model versioning, deployment, and monitoring basics.'),
    s('model-deployment', 'Model Deployment', 'Pickle, ONNX, REST APIs, and batch scoring.'),
    s('experiment-tracking', 'Experiment Tracking', 'MLflow, metrics logging, and reproducibility.'),
    s('time-series-ml', 'Time Series ML', 'Lag features, rolling windows, and forecasting models.'),
    s('recommender-systems', 'Recommender Systems', 'Collaborative filtering and content-based approaches.'),
    s('anomaly-detection', 'Anomaly Detection', 'Isolation Forest, statistical methods, and use cases.'),
    s('interpretability', 'Model Interpretability', 'SHAP, LIME, and explaining predictions to stakeholders.'),
    s('capstone-project', 'ML Capstone Project', 'End-to-end classification or regression project.'),
  ],

  'artificial-intelligence': [
    s('ai-history', 'History of AI', 'AI milestones from Turing to modern deep learning systems.'),
    s('ai-paradigms', 'AI Paradigms', 'Symbolic AI, connectionism, and hybrid approaches.'),
    s('problem-solving', 'Problem Solving', 'State spaces, goal states, and formulation of AI problems.'),
    s('search-bfs-dfs', 'BFS & DFS', 'Uninformed search strategies and completeness properties.'),
    s('search-heuristic', 'Heuristic Search', 'Greedy best-first and A* algorithm fundamentals.'),
    s('game-trees', 'Game Trees & Minimax', 'Adversarial search, minimax, and alpha-beta pruning.'),
    s('knowledge-representation', 'Knowledge Representation', 'Facts, rules, frames, and semantic networks.'),
    s('logic-propositional', 'Propositional Logic', 'AND, OR, NOT, implications, and inference rules.'),
    s('logic-first-order', 'First-Order Logic', 'Predicates, quantifiers, and knowledge base reasoning.'),
    s('expert-systems', 'Expert Systems', 'Rule-based systems, inference engines, and MYCIN-style design.'),
    s('planning', 'Automated Planning', 'STRIPS, plan spaces, and classical planning algorithms.'),
    s('reasoning-under-uncertainty', 'Reasoning Under Uncertainty', 'Bayesian networks and probabilistic reasoning.'),
    s('nlp-symbolic', 'Symbolic NLP', 'Parsing, grammars, and early language understanding.'),
    s('computer-vision-classic', 'Classic Computer Vision', 'Edge detection, HOG, and pre-deep-learning CV.'),
    s('robotics-intro', 'Robotics Introduction', 'Sensors, actuators, and sense-plan-act loops.'),
    s('ai-ethics', 'AI Ethics', 'Alignment, transparency, and societal impact of AI systems.'),
    s('modern-ai-landscape', 'Modern AI Landscape', 'Deep learning, LLMs, and the current AI stack.'),
    s('ai-vs-ml-vs-dl', 'AI vs ML vs DL', 'Clarifying terminology and scope of each field.'),
    s('agents-intro', 'Intelligent Agents', 'PEAS framework, agent types, and environments.'),
    s('future-trends', 'Future Trends', 'Multimodal AI, embodied AI, and research frontiers.'),
  ],

  nlp: [
    s('nlp-overview', 'NLP Overview', 'Natural language processing tasks, challenges, and applications.'),
    s('text-preprocessing', 'Text Preprocessing', 'Lowercasing, punctuation, stop words, and normalization.'),
    s('tokenization', 'Tokenization', 'Word tokenization, subword algorithms, and SentencePiece.'),
    s('stemming-lemmatization', 'Stemming & Lemmatization', 'Reducing words to root forms with NLTK and spaCy.'),
    s('ngrams', 'N-grams', 'Character and word n-grams for language modeling features.'),
    s('bag-of-words', 'Bag of Words', 'CountVectorizer, document-term matrices, and sparsity.'),
    s('tf-idf', 'TF-IDF', 'Term frequency-inverse document frequency weighting scheme.'),
    s('word-embeddings', 'Word Embeddings', 'Word2Vec, GloVe, and dense vector representations.'),
    s('embeddings-training', 'Training Embeddings', 'CBOW, Skip-gram, negative sampling, and vector arithmetic.'),
    s('sequence-models-intro', 'Sequence Models Intro', 'Why sequences need specialized architectures.'),
    s('rnn-nlp', 'RNNs for NLP', 'Recurrent networks for tagging, classification, and generation.'),
    s('attention-mechanism', 'Attention Mechanism', 'Query-key-value attention and its role in modern NLP.'),
    s('transformers-intro', 'Transformers Introduction', 'Self-attention, encoder-decoder, and positional encoding.'),
    s('bert', 'BERT', 'Masked language modeling, fine-tuning BERT for downstream tasks.'),
    s('gpt-models', 'GPT Models', 'Autoregressive language models and generative text.'),
    s('text-classification', 'Text Classification', 'Sentiment analysis, topic classification, and fine-tuning.'),
    s('named-entity-recognition', 'Named Entity Recognition', 'Span labeling, BIO tagging, and NER models.'),
    s('pos-tagging', 'Part-of-Speech Tagging', 'Grammatical tagging with HMMs and neural taggers.'),
    s('machine-translation', 'Machine Translation', 'Seq2seq, attention, and transformer translation systems.'),
    s('question-answering', 'Question Answering', 'Extractive and generative QA architectures.'),
    s('summarization', 'Text Summarization', 'Extractive vs abstractive summarization approaches.'),
    s('spacy-pipeline', 'spaCy Pipeline', 'Tokenization, NER, and custom pipeline components.'),
    s('huggingface-intro', 'Hugging Face Intro', 'Transformers library, model hub, and tokenizers.'),
    s('prompting-nlp', 'Prompting for NLP', 'Zero-shot, few-shot, and instruction tuning for NLP tasks.'),
    s('evaluation-nlp', 'NLP Evaluation', 'BLEU, ROUGE, perplexity, and human evaluation.'),
    s('multilingual-nlp', 'Multilingual NLP', 'Cross-lingual models and translation for low-resource languages.'),
    s('nlp-production', 'NLP in Production', 'Serving models, latency, batching, and monitoring.'),
    s('nlp-ethics', 'NLP Ethics', 'Bias in language models, toxicity, and content moderation.'),
    s('rag-nlp', 'RAG for NLP', 'Retrieval-augmented generation for grounded text applications.'),
    s('nlp-capstone', 'NLP Capstone', 'Build a text classification or QA mini-project.'),
  ],

  rnn: [
    s('sequences-intro', 'Sequences Introduction', 'Sequential data types: text, time series, audio, and video.'),
    s('rnn-architecture', 'RNN Architecture', 'Recurrent connections, hidden state, and unrolling through time.'),
    s('forward-pass', 'Forward Pass', 'Computing outputs step-by-step across sequence length.'),
    s('bptt', 'Backprop Through Time', 'Gradient flow through unrolled RNN and vanishing gradients.'),
    s('lstm-architecture', 'LSTM Architecture', 'Forget, input, output gates, and cell state mechanics.'),
    s('lstm-applications', 'LSTM Applications', 'Language modeling, sentiment, and sequence prediction.'),
    s('gru-architecture', 'GRU Architecture', 'Reset and update gates — lighter alternative to LSTM.'),
    s('gru-vs-lstm', 'GRU vs LSTM', 'Trade-offs in parameters, training speed, and performance.'),
    s('bidirectional-rnn', 'Bidirectional RNNs', 'Forward and backward passes for context from both directions.'),
    s('stacked-rnn', 'Stacked RNNs', 'Multi-layer recurrent networks for hierarchical features.'),
    s('sequence-to-sequence', 'Sequence-to-Sequence', 'Encoder-decoder architecture for translation and summarization.'),
    s('teacher-forcing', 'Teacher Forcing', 'Training seq2seq models with ground-truth vs predicted inputs.'),
    s('attention-rnn', 'Attention in RNNs', 'Bahdanau attention connecting encoder and decoder.'),
    s('time-series-rnn', 'Time Series with RNNs', 'Forecasting, windowing, and multivariate sequences.'),
    s('padding-masking', 'Padding & Masking', 'Handling variable-length sequences in batches.'),
    s('pytorch-rnn', 'RNN in PyTorch', 'nn.RNN, nn.LSTM, nn.GRU modules and training loops.'),
    s('keras-rnn', 'RNN in Keras', 'Sequential models with LSTM/GRU layers.'),
    s('rnn-limitations', 'RNN Limitations', 'Long-range dependencies and why transformers emerged.'),
    s('rnn-tuning', 'RNN Hyperparameter Tuning', 'Hidden size, layers, dropout, and learning rate.'),
    s('rnn-capstone', 'RNN Capstone', 'Train an LSTM for text generation or time series forecasting.'),
  ],

  ann: [
    s('neurons-biology', 'Biological Inspiration', 'How artificial neurons relate to biological neurons.'),
    s('perceptron', 'The Perceptron', 'Single-layer network, linear separability, and limitations.'),
    s('activation-functions', 'Activation Functions', 'Sigmoid, tanh, ReLU, Leaky ReLU, and softmax.'),
    s('multi-layer-networks', 'Multi-Layer Networks', 'Hidden layers, universal approximation, and depth.'),
    s('forward-propagation', 'Forward Propagation', 'Matrix operations through layers to compute outputs.'),
    s('loss-functions', 'Loss Functions', 'MSE, cross-entropy, and choosing the right loss.'),
    s('backpropagation', 'Backpropagation', 'Chain rule, gradient computation, and weight updates.'),
    s('gradient-descent', 'Gradient Descent', 'Batch, mini-batch, and stochastic gradient descent.'),
    s('learning-rate', 'Learning Rate', 'Fixed, decay, and adaptive learning rate schedules.'),
    s('optimizers', 'Optimizers', 'SGD, Momentum, Adam, RMSprop, and when to use each.'),
    s('weight-initialization', 'Weight Initialization', 'Xavier, He initialization, and avoiding dead neurons.'),
    s('batch-normalization', 'Batch Normalization', 'Normalizing activations for faster, stable training.'),
    s('dropout', 'Dropout Regularization', 'Random neuron dropout to prevent overfitting.'),
    s('overfitting-ann', 'Overfitting in ANNs', 'Early stopping, L2 regularization, and data augmentation.'),
    s('hyperparameter-search', 'Hyperparameter Search', 'Grid search and random search for network design.'),
    s('pytorch-ann', 'Building ANNs in PyTorch', 'nn.Module, Linear layers, and training loops.'),
    s('keras-ann', 'Building ANNs in Keras', 'Sequential API, compile, fit, and evaluate.'),
    s('classification-ann', 'Classification with ANNs', 'Softmax output, categorical cross-entropy, and metrics.'),
    s('regression-ann', 'Regression with ANNs', 'Linear output layer and regression-specific considerations.'),
    s('visualizing-training', 'Visualizing Training', 'Loss curves, accuracy plots, and TensorBoard basics.'),
    s('debugging-nn', 'Debugging Neural Networks', 'NaN gradients, dead ReLUs, and common training failures.'),
    s('ann-capstone', 'ANN Capstone', 'Train a feedforward network on a tabular or MNIST dataset.'),
  ],

  cnn: [
    s('cnn-motivation', 'Why CNNs?', 'Spatial hierarchies in images and parameter sharing benefits.'),
    s('convolution-operation', 'Convolution Operation', 'Filters, kernels, stride, and feature map computation.'),
    s('padding-stride', 'Padding & Stride', 'Same vs valid padding and output dimension formulas.'),
    s('pooling-layers', 'Pooling Layers', 'Max pooling, average pooling, and spatial downsampling.'),
    s('cnn-architecture', 'CNN Architecture', 'Conv-pool stacks, flatten, and fully connected classifier.'),
    s('feature-maps', 'Feature Maps', 'What filters learn at each layer — edges to objects.'),
    s('popular-architectures', 'Popular Architectures', 'LeNet, AlexNet, VGG, ResNet overview.'),
    s('residual-connections', 'Residual Connections', 'Skip connections, vanishing gradients, and ResNet blocks.'),
    s('transfer-learning', 'Transfer Learning', 'Pre-trained models, fine-tuning, and feature extraction.'),
    s('data-augmentation', 'Data Augmentation', 'Rotation, flip, crop, and synthetic training data.'),
    s('image-classification', 'Image Classification', 'Training and evaluating CNN classifiers end-to-end.'),
    s('object-detection-intro', 'Object Detection Intro', 'Bounding boxes, IoU, and detection vs classification.'),
    s('yolo-intro', 'YOLO Introduction', 'Single-shot detectors and real-time detection concepts.'),
    s('segmentation-intro', 'Segmentation Intro', 'Semantic vs instance segmentation overview.'),
    s('cnn-pytorch', 'CNNs in PyTorch', 'nn.Conv2d, nn.MaxPool2d, and torchvision models.'),
    s('cnn-keras', 'CNNs in Keras', 'Conv2D, MaxPooling2D, and pretrained applications.'),
    s('regularization-cnn', 'CNN Regularization', 'Dropout, batch norm, and weight decay for CNNs.'),
    s('interpretability-cnn', 'CNN Interpretability', 'Grad-CAM, filter visualization, and saliency maps.'),
    s('deployment-cnn', 'Deploying CNN Models', 'ONNX, TensorRT, and edge deployment considerations.'),
    s('cnn-capstone', 'CNN Capstone', 'Fine-tune a pretrained model for a custom image dataset.'),
  ],

  'generative-ai': [
    s('genai-overview', 'Generative AI Overview', 'Generative vs discriminative models and the GenAI landscape.'),
    s('llm-fundamentals', 'LLM Fundamentals', 'Token prediction, context windows, and scaling laws.'),
    s('transformer-recap', 'Transformer Recap', 'Self-attention, positional encoding, and decoder-only models.'),
    s('gpt-family', 'GPT Model Family', 'GPT-2 through GPT-4 evolution and capabilities.'),
    s('open-source-llms', 'Open Source LLMs', 'Llama, Mistral, and the open-weight ecosystem.'),
    s('prompt-engineering', 'Prompt Engineering', 'Zero-shot, few-shot, chain-of-thought, and role prompting.'),
    s('prompt-patterns', 'Prompt Patterns', 'ReAct, tree-of-thought, and structured output prompting.'),
    s('fine-tuning-intro', 'Fine-Tuning Introduction', 'When to fine-tune vs prompt vs RAG.'),
    s('lora-peft', 'LoRA & PEFT', 'Parameter-efficient fine-tuning with low-rank adapters.'),
    s('full-fine-tuning', 'Full Fine-Tuning', 'Dataset preparation, training loops, and evaluation.'),
    s('instruction-tuning', 'Instruction Tuning', 'Supervised fine-tuning for helpful, aligned assistants.'),
    s('rlhf', 'RLHF Overview', 'Reinforcement learning from human feedback and reward models.'),
    s('rag-fundamentals', 'RAG Fundamentals', 'Retrieval-augmented generation architecture and benefits.'),
    s('vector-databases', 'Vector Databases', 'Embeddings storage, similarity search, and Pinecone/Chroma.'),
    s('chunking-strategies', 'Chunking Strategies', 'Document splitting, overlap, and metadata for RAG.'),
    s('evaluation-llm', 'Evaluating LLMs', 'BLEU, human eval, LLM-as-judge, and benchmark suites.'),
    s('hallucination', 'Hallucination Mitigation', 'Grounding, citation, and confidence calibration.'),
    s('safety-guardrails', 'Safety & Guardrails', 'Content filtering, moderation, and responsible deployment.'),
    s('multimodal-genai', 'Multimodal GenAI', 'Vision-language models, DALL-E, and image generation.'),
    s('diffusion-models', 'Diffusion Models', 'Denoising diffusion and Stable Diffusion concepts.'),
    s('agents-llm', 'LLM Agents', 'Tool use, planning, and autonomous agent loops with LLMs.'),
    s('langchain-intro', 'LangChain Introduction', 'Chains, agents, memory, and tool integration patterns.'),
    s('cost-optimization', 'Cost Optimization', 'Token budgeting, caching, and model routing strategies.'),
    s('deployment-llm', 'Deploying LLMs', 'vLLM, Ollama, Azure OpenAI, and inference optimization.'),
    s('genai-capstone', 'GenAI Capstone', 'Build a RAG chatbot or fine-tuned assistant mini-project.'),
  ],

  'agentic-ai': [
    s('agents-overview', 'AI Agents Overview', 'Autonomy levels, agent architectures, and use cases.'),
    s('agent-components', 'Agent Components', 'Perception, planning, memory, tools, and action modules.'),
    s('react-pattern', 'ReAct Pattern', 'Reasoning and acting interleaved in agent loops.'),
    s('tool-use', 'Tool Use', 'Function calling, API integration, and tool-augmented agents.'),
    s('function-calling', 'Function Calling', 'OpenAI/Azure function schemas and structured tool invocation.'),
    s('memory-systems', 'Agent Memory', 'Short-term, long-term, episodic memory for agents.'),
    s('planning-agents', 'Planning Agents', 'Task decomposition, goal setting, and plan execution.'),
    s('reflection', 'Self-Reflection', 'Critique loops, self-correction, and iterative improvement.'),
    s('multi-agent-intro', 'Multi-Agent Introduction', 'Why multiple agents and collaboration patterns.'),
    s('agent-roles', 'Agent Roles', 'Specialist agents, orchestrator, and role assignment.'),
    s('communication', 'Agent Communication', 'Message passing, shared state, and protocols.'),
    s('orchestration', 'Orchestration Frameworks', 'LangGraph, AutoGen, and CrewAI patterns.'),
    s('langgraph', 'LangGraph Deep Dive', 'State graphs, nodes, edges, and conditional routing.'),
    s('human-in-loop', 'Human-in-the-Loop', 'Approval gates, feedback, and supervised autonomy.'),
    s('evaluation-agents', 'Evaluating Agents', 'Task success rate, tool accuracy, and trajectory analysis.'),
    s('error-recovery', 'Error Recovery', 'Retry logic, fallback tools, and graceful degradation.'),
    s('security-agents', 'Agent Security', 'Prompt injection, tool sandboxing, and permission boundaries.'),
    s('cost-latency', 'Cost & Latency', 'Token usage, parallel tool calls, and optimization.'),
    s('production-agents', 'Production Agent Pipelines', 'Logging, tracing, and deployment patterns.'),
    s('observability', 'Agent Observability', 'LangSmith, OpenTelemetry, and debugging agent runs.'),
    s('case-study-research', 'Case Study: Research Agent', 'Multi-step research with search and synthesis.'),
    s('case-study-coding', 'Case Study: Coding Agent', 'Code generation, testing, and iteration loops.'),
    s('case-study-data', 'Case Study: Data Agent', 'SQL generation, analysis, and visualization agents.'),
    s('agentic-capstone', 'Agentic AI Capstone', 'Build a multi-tool agent with orchestration framework.'),
  ],
};

module.exports = { PATHS, s };
